### PR TITLE
Fix issue #141

### LINKED ISSUE #141: Mistake- "WSO2 Identity Server Privacy Policy" web page
Please follow the attached document: ( issues are highlighted)

https://docs.google.com/document/d/17WeJPSUOzDf8kf8woSNZmKZxqVmQ1MPfu2xzYr74f_A/edit

### PR DESCRIPTION
**Pull request by thivi**
image
image

### CODE REVIEW

File: apps/user-portal/src/components/applications/application-search.tsx [hunk 1]
```diff
@@ -224,13 +224,13 @@ export const ApplicationSearch: FunctionComponent<ApplicationSearchProps> = (
                                 <Field
                                     size="small"
                                     type="submit"
-                                    value={ t("common:search") as string }
+                                    value={ t("common:search").toString() }
```
Comment (brionmario) [inline apps/user-portal/src/components/applications/application-search.tsx:227]: Is this necessary?
